'use strict';(function(){Array.prototype.get=Array.prototype.get||function(search){return _(this).findWhere(search);};inproces.filter('nospace',function(){return function(e){return e?e.replace(/ /g,''):'';};}).filter('friendlyurl',function(){return function(result){result=result.replace(/[^0-9a-zA-Z|_|-]/g,'-');result=result.replace(/-+/g,'-');result=result.replace(/^-+|-+$/g,'');return result;};}).filter('keyboardShortcut',function($window){return function(str){if(!str){return;}
var keys=str.split('-');var isOSX=/Mac OS X/.test($window.navigator.userAgent);var seperator=(!isOSX||keys.length>2)?'+':'';var abbreviations={M:isOSX?'⌘':'Ctrl',A:isOSX?'Option':'Alt',S:'Shift'};return keys.map(function(key,index){var last=index==keys.length-1;return last?key:abbreviations[key];}).join(seperator);};}).factory('execute_in_application',function(){return{'request':function(config){var str=window.location.search;var params={};str.replace(new RegExp("([^?=&]+)(=([^&]*))?","g"),function($0,$1,$2,$3){params[$1]=$3;});if(params.execution_in_application){if(!config.params){config.params={};}
config.params.execution_in_application=params.execution_in_application;}
return config;},'response':function(response){return response;}};}).factory('ipUtils',function($q,$http){var _currentViewport='';return{detailStore:function(data,fields){var result=[];result.fields=fields;try{if(data[fields[0]]&&data[fields[0]].length){for(var i=0;i<data[fields[0]].length;i++){var obj={};fields.forEach(function(field){obj[field]=data[field]?data[field][i]:null;});result.push(obj);}}}catch(e){return[{error:e}];}
result.sync=function(data){angular.forEach(this.fields,function(field){data[field]=_.pluck(this,field);},this);return data;};return result;},evaluate:function(params){var url='/entiteitproxy?action=evaluate';return $http({method:'GET',url:url,params:params});},name:function(fullname,part){var names=angular.isArray(fullname)?fullname:[fullname];var i,j,name;var results=[];for(i=0;i<names.length;i++){name=names[i]||'';var namecomponents=name.split('/');var result={};for(j=0;j<namecomponents.length;j++){var keyvalue=namecomponents[j].split('=');if(!result[keyvalue[0]]){result[keyvalue[0]]=keyvalue[1];}else{if(!angular.isArray(result[keyvalue[0]])){result[keyvalue[0]]=[].concat(result[keyvalue[0]]);}
result[keyvalue[0]].push(keyvalue[1]);}}
if(result[part]){results.push(result[part]);}else{results.push(undefined);}}
return angular.isArray(fullname)?results:results[0];},viewportDetect:function(onChange){if(arguments.length===0){return $('#viewportDetect div:visible').data('viewport');}
$(window).resize(function(){var viewport=$('#viewportDetect div:visible').data('viewport');if(_currentViewport===''){_currentViewport=viewport;}
if(_currentViewport!==viewport){var prevViewport=_currentViewport;_currentViewport=viewport;onChange(_currentViewport,prevViewport);}});}};});})();